### PR TITLE
Context for why small batches are better

### PR DESCRIPTION
**Pull request by iw-ezequiel**

### CODE REVIEW

**Comment by arctangent** [comment]
Is this a better source?

https://cloud.google.com/architecture/devops/devops-process-working-in-small-batches

**Comment by iw-ezequiel** [comment]
> Is this a better source?
> 
> https://cloud.google.com/architecture/devops/devops-process-working-in-small-batches

Hi Jacob, I think that's a great guide to small batches from a scientific point of view, and several of those points are captured in the page. I'm specifically looking for the envelope stuffing example though (unfortunately Eric Ries's blog post on this is very old and the page is rather broken) as a more "emotional" illustration of why it actually works even if it may sound entirely counterintuitive.

**Comment by arctangent** [comment]
As a software engineer, I'm comfortable with scientific arguments :-)

Either way, if you're eager to use the envelope example then there are much better sources than that Medium page:

- https://blog.gembaacademy.com/2014/07/29/whats-faster-one-piece-flow-or-mass-production-watch-this-envelope-stuffing-simulation-to-find-out/

- https://www.inspira-uk.com/blog/lean-thinking-lessons-from-packing-envelopes/

**Comment by iw-ezequiel** [comment]
I'd dare say we all love scientific arguments, but winning hearts (as well as minds!) with science only can be quite difficult 😁When it comes to the other articles you linked (thanks for that!), it would be good to have your thoughts on what you see they add on top of the Medium post? Perhaps we need to build some of that into the framework itself.

**Comment by arctangent** [comment]
Happy to let whoever is reviewing this merge make a decision.

**Review by andyblundell — APPROVED** [review]

**Pull request merged**
