### PR TITLE
Feature/tex 4735 aws fis sample code

### PR DESCRIPTION
**Pull request by JohnEllwoodBJSS**

### CODE REVIEW

**Review by iw-ezequiel — DISMISSED** [review]
This is great John, thanks a lot. Will add to the Chaos Engineering blog post that we're publishing soon :)

**Comment by andyblundell** [comment]
Great stuff, thanks @JohnEllwoodBJSS - only suggestion is to add a link to the new folder from quality-check.md in the endorsed-solution column: "For AWS services: <<link to new folder>>" - cool?

**Comment by JohnEllwoodBJSS** [comment]
> Great stuff, thanks @JohnEllwoodBJSS - only suggestion is to add a link to the new folder from quality-check.md in the endorsed-solution column: "For AWS services: <>" - cool?

Updated - please can you re-review @andyblundell ?

**Review by andyblundell — COMMENTED** [review]
Hi, great stuff, thanks - just a couple more quick thoughts (sorry) -
1. Can we add a brief readme to /aws-fis/ (since that's the entry point from quality-checks.md) to say this is a folder of sample code we've used
2. Can we replace the references to texastest.uk with exampledomain.com or something like that?

**Comment by JohnEllwoodBJSS** [comment]
> Hi, great stuff, thanks - just a couple more quick thoughts (sorry) -
> 
> 1. Can we add a brief readme to /aws-fis/ (since that's the entry point from quality-checks.md) to say this is a folder of sample code we've used
> 2. Can we replace the references to texastest.uk with exampledomain.com or something like that?

Sure thing Andy, I'll make these changes shortly

**Comment by JohnEllwoodBJSS** [comment]
> Hi, great stuff, thanks - just a couple more quick thoughts (sorry) -
> 
> 1. Can we add a brief readme to /aws-fis/ (since that's the entry point from quality-checks.md) to say this is a folder of sample code we've used
> 2. Can we replace the references to texastest.uk with exampledomain.com or something like that?

quality checks.md should be sorted now

**Review by andyblundell — APPROVED** [review]

**Pull request merged**
